Make compatible to modern SQLalchemy
At least I guess that's what caused this error on startup:

Traceback (most recent call last):
[...]
File "nina_xmpp/db.py", line 48, in initialize
  conn.execute(select([func.InitSpatialMetaData(True, 'WGS84')]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[...]
sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other columns clause element expected, got [<sqlalchemy.sql.functions.Function at 0x7f9f9153e8d0; InitSpatialMetaData>]. Did you mean to say select(<sqlalchemy.sql.functions.Function at 0x7f9f9153e8d0; InitSpatialMetaData>)?